# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipGeocode',
            fields=[
                ('zip', models.TextField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.IntegerField()),
                ('daylight_savings', models.BooleanField()),
            ],
            options={
                'db_table': 'zip_geocode',
            },
        ),
    ]
