# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20160305_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduserdata',
            options={'verbose_name_plural': 'extended user data'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'specialties'},
        ),
    ]
